### ISSUE TITLE
EULA not displayed

### ISSUE THREAD

**Issue by dominik0711** [andreyvit/create-dmg#33]
The eula command switch seems to have no effect? When does the EULA will be shown to the user? What file format should the document have?

Thanks

**Comment by kaloyan-raev** [comment]
You may be affected by the issue I described in https://github.com/andreyvit/yoursway-create-dmg/pull/34

**Comment by VANSMOOKEYMAWA** [comment]
Leave a comment:FAIR

**Comment by aglv** [comment]
After my experience,
* Adding an RTF EULA fails when the RTF was generated from MS Word;
* Adding an RTF EULA fails if the RTF contains long lines of text or sentences.

The second problem is fixed in my fork.

**Comment by aonez** [comment]
> * Adding an RTF EULA fails if the RTF contains long lines of text or long sentences.

Fixed in #62

**Comment by aonez** [comment]
> * Adding an RTF EULA fails when the RTF was generated from MS Word

Fixed in #63
