### ISSUE TITLE
Is it possible to launch at startup?

### ISSUE THREAD

**Issue by drown-zed** [andreyvit/create-dmg#40]
I need the installed app to launch at startup, is it possible to do so during the dmg file installation?

**Comment by andreyvit** [comment]
Nope, unfortunately, it's not.

**Comment by sainianil** [comment]
Add below code in apple script after installation, will solve your problem

```
#Find application path
tell application "Finder"
	set myPath to (POSIX path of (application file id "Your app identifier" as alias))
end tell

#Add your app to login items
tell application "System Events"
	make new login item at end of login items with properties {name:"Your app name", path:myPath, hidden:false}
end tell
```

**Comment by aonez** [comment]
@sainianil this will only work in the computer that creates the DMG. This code is not portable.

As @andreyvit this is not possible to do.
