### ISSUE TITLE
Add homebrew formula

### ISSUE THREAD

**Issue by MartinDelille** [andreyvit/create-dmg#44]
This would be very convenient to install this nice script using [Homebrew](http://brew.sh). I'm on the way to pull it from [my fork](https://github.com/MartinDelille/homebrew-core/tree/create-dmg), but in order to do that we need the following to be done:
- [x] Create a release (ie: 1.0.0.2)
- [x] Find a way to handle differently the `support` directory (I'm not sure it'll pass the Homebrew owner validation to create a `/usr/local/bin/support` directory)

What do you think?

**Comment by MartinDelille** [comment]
Is it possible to create the release ?

**Comment by MartinDelille** [comment]
Anyone? @andreyvit ?

**Comment by MartinDelille** [comment]
In fact the first thing would be to change the way to access the support directory to a configurable one.

**Comment by MartinDelille** [comment]
@andreyvit up

**Comment by MartinDelille** [comment]
@andreyvit Any idea about the second action?

**Comment by aonez** [comment]
This will be indeed very useful 👍

**Comment by aonez** [comment]
@MartinDelille I'm not really familiar with brew formulas. But wouldn't it be:
`/usr/local/bin/create-dmg/support`

Do you think any of the source files need to be dismissed in the release, or just packing the source will be enough?

**Comment by MartinDelille** [comment]
I contributed to several homebrew formula but the blocking thing right now is to publish a release: https://github.com/andreyvit/create-dmg/releases

**Comment by aonez** [comment]
There you go: https://github.com/andreyvit/create-dmg/releases/tag/v1.0.0.3

**Comment by MartinDelille** [comment]
Great! I created the formula and started the pull request process here: https://github.com/Homebrew/homebrew-core/pull/32496

Maybe you should subscribe to it because the maintainer will surely ask question and present requirement. Publishing a brew compatible formula is not an easy thing.

**Comment by aonez** [comment]
Subscribed, I'll help anyway I can.

**Comment by MartinDelille** [comment]
Ok I improved it quite a bit but it doesn't install yet.

**Comment by aonez** [comment]
@MartinDelille again I've never did a brew formula, but maybe the `test` part is what's failing? How can it be tested locally?

**Comment by aonez** [comment]
any update on this @MartinDelille?

**Comment by aonez** [comment]
Job done @MartinDelille! I think more than one will be happy to have this script in brew 👍 Salut!

**Comment by MartinDelille** [comment]
You rock!
