### ISSUE TITLE
Handling error after running applescript

### ISSUE THREAD

**Issue by linjackson78** [andreyvit/create-dmg#45]
From time to time, create-dmg exits successfully, but I get a dmg of problems, such as wrong positioning of app icon, no background set, etc.

I found the one-line clue:

```
/var/folders/pz/gnq0qm5d0xq6drrff4q8tqm80000gp/T/createdmg.ZeDZXwco:435:450: execution error: Finder got an error: Can’t set toolbar visible of container window of disk "mydisk" to false. (-10006)
```

Looks like there may be errors when running 

```
"/usr/bin/osascript" "${APPLESCRIPT}" "${VOLUME_NAME}" || true
```

and simply ignoring those potential error may cause confusion.

**Comment by leominov** [comment]
Check it: https://github.com/andreyvit/create-dmg/pull/48

**Comment by maxisme** [comment]
ran with `sudo` and no error... Feels like some cached permissions...

**Comment by maxisme** [comment]
Make sure the `${APPLESCRIPT}` opens the finder window
