### ISSUE TITLE
Error -10810 - not sure what that means, but the installer window size is very different now.

### ISSUE THREAD

**Issue by cfriedt** [andreyvit/create-dmg#53]
Running Applescript: /usr/bin/osascript "/var/folders/db/symwszkn31z9p8rthv3fsy4r0000gn/T/createdmg.Jl54F3LS" "GNURadio-3.7.10.1-94ee402"
/var/folders/db/symwszkn31z9p8rthv3fsy4r0000gn/T/createdmg.Jl54F3LS:85:89: execution error: An error of type -10810 has occurred. (-10810)
Done running the applescript...
Fixing permissions...

**Comment by aonez** [comment]
@cfriedt you solved this issue?

**Comment by cfriedt** [comment]
Let's go with yes. It's been so long at this point and the installer mostly works.
