### ISSUE TITLE
.VolumeIcon.icns disappears on High Sierra 

### ISSUE THREAD

**Issue by akira0fujita** [andreyvit/create-dmg#57]
Hi,

On high sierra, it seems that ".VolumeIcon.icns" file disappears after exec applescript of create-dmg. Is it known issue?

e.g.
./create-dmg --window-size 600 500 --text-size 12 --background "./dmg_background.pdf" --icon-size 96 --volname "HOGEVOL" --volicon "./dmg_resources/dmg_icon.icns"  --icon "HOGEVOL" 185 307 --app-drop-link 414 307 "./HOGEVOL_1.0.0.3.dmg" "./dmg_source" 

<snip>

ls -a MOUNT_DIR :
.				.background			DistributionSummary.plist	hoge.app
..				.fseventsd			ExportOptions.plist
.VolumeIcon.icns		Applications			Packaging.log

Running Applescript: /usr/bin/osascript "/var/folders/65/x5p5_y2j2zq7fpjrq7xjj0bw0000gn/T/createdmg.jZLEkFMZ" "HOGEVOL"
waited 1 seconds for .DS_STORE to be created.
Done running the applescript...
/var/folders/65/x5p5_y2j2zq7fpjrq7xjj0bw0000gn/T/createdmg.jZLEkFMZ

ls -a MOUNT_DIR:
.				.background			DistributionSummary.plist	hoge.app
..				.fseventsd			ExportOptions.plist
.DS_Store			Applications			Packaging.log           <--- .VolumeIcon.icns is removed !

**Comment by SethAluma** [comment]
I've just noticed the same thing. I copied the code that copies the icon, and pasted it just below the apple script section to copy the icon over again after it's removed (todays my first day even using a Mac, so that's the best I can do for now, lol)
Maybe someone out there can figure out why it removes it.

**Comment by allyusd** [comment]
Like @SethAluma, I change VOLUME_ICON_FILE and APPLESCRIPT order.

**Comment by aonez** [comment]
@andreyvit do you remember what this code in the AppleScript does?

```applescript
update without registering applications
```

Because is the one that causes this issue. I can't find information about it, but commenting this code worked for me, tested from 10.9-10.13. If you don't recall this one being important, I'll just remove those lines.

**Comment by aonez** [comment]
Or do the @SethAluma and @allyusd move maybe is better, if that code is important.

**Comment by andreyvit** [comment]
@aonez The script comes from Adium, here's the latest version there: https://github.com/adium/adium/blob/master/Release/dmg_adium.scpt — it does seem to still contain `update without registering applications`.

**Comment by andreyvit** [comment]
@aonez Although that script was last updated 7 years ago, so just do whatever is necessary :-)
