### ISSUE TITLE
Various problems processing long lines in EULA file

### ISSUE THREAD

**Issue by sidney** [andreyvit/create-dmg#62]
When the --eula option specifies a file that contains lines longer than 1000 characters, the code that breaks up the long lines so that they are not too long for the Mac OS resource handling is incorrect.

The most obvious error is that a new line is inserted after every "." character.

`1.5.2. This is a short sentence. It starts a long paragraph of longer than 1000 characters`

becomes

```
1.
5.
2.
This is a short sentence.
It starts a long paragraph of longer than 1000 characters
```

It will also exit with a failure if given a file containing a sequence more than 1000 characters that has no newlines and no "."

I have a pull request I'm preparing that both simplifies the existing code and fixes this.

**Comment by aonez** [comment]
Thanks a lot @sidney! Merged 😊

This one solves:

> Adding an RTF EULA fails if the RTF contains long lines of text or long sentences.
