### ISSUE TITLE
EULA file in Microsoft WordPad format can't be processed

### ISSUE THREAD

**Issue by sidney** [andreyvit/create-dmg#63]
This bug was mentioned in a comment in issue #33 but since that issue has no solution and is really two separate problems, I have created issue #62 for the problems caused by long lines and this one for the inability to process RTF files that are created using Microsoft WordPad, and will submit separate pull requests for each.

**Comment by aonez** [comment]
Fixed in #65

**Comment by aonez** [comment]
@sidney this one fully solves:

> Adding an RTF EULA fails when the RTF was generated from MS Word;

Or just part of it? Since you've said

> issue #33 but since that issue has no solution

**Comment by sidney** [comment]
@aonez Pull request #64 for issue #62 fixes problems with files with long lines whether they are text or RTF. The pull request #65 for this issue fixes a separate problem with RTF files that are generated by Microsoft WordPad, that they contain null characters which break processing of the resource. Together these two pull requests resolve all the problems mentioned in the comments in issue #33

**Comment by aonez** [comment]
Then I'll close #33 as fully fixed 😊 thanks a lot @sidney!
