### ISSUE TITLE
New option for QuickLook drop link

### ISSUE THREAD

**Issue by nunopedrosa** [andreyvit/create-dmg#70]
I made a small change to the script, to be able to handle QuickLook plugins installs:

> --ql-drop-link x y
>       make a drop link to QuickLook install dir, at location x,y

It's just a copy of "**app-drop-link**", but works fine, if anyone is interested.

**Comment by aonez** [comment]
Looks cool for me! Make a pull request and lets see :)

**Comment by nunopedrosa** [comment]
Thanks! I'm trying to push a new branch (quicklook), but I have no permissions:

> Authentication failed. You may not have permission to access the repository [...]

I can only open the pull request after pushing a new branch, right?

**Comment by nunopedrosa** [comment]
Ah! So that's what I was missing! Thank you! The request is created.

**Comment by aonez** [comment]
Pull request here #71

**Comment by RoyiAvital** [comment]
@aonez ,
Can one create arbitrary Drop Link?

**Comment by aonez** [comment]
@RoyiAvital not right now, would be a great addition! Maybe a minor modification of the #71 pull will be enough 😊

**Comment by zetenynagy** [comment]
@RoyiAvital - if you're still interested:
> Can one create arbitrary Drop Link?

I made a small modification to the script based on what @nunopedrosa did. See pull request #151

**Comment by Pjumpod** [comment]
I do not understand, what is the x, y in an argument. even though the x,y in --app-drop-link.
